In [8]:
import pandas as pd
import numpy as np

from sklearn import *
from sklearn.linear_model import *

In [16]:
a = pd.DataFrame(zip([ 7921, 5184, 8836, 4761 ]))
a

0
0  7921
1  5184
2  8836
3  4761

In [17]:
b = preprocessing.MinMaxScaler().fit_transform(a)


array([[ 0.77546012],
       [ 0.10380368],
       [ 1.        ],
       [ 0.        ]])

In [19]:
c = preprocessing.MaxAbsScaler().fit_transform(a)
c

array([[ 0.89644636],
       [ 0.58669081],
       [ 1.        ],
       [ 0.53881847]])

In [34]:
d = preprocessing.StandardScaler(with_mean=True, with_std=False).fit_transform(c)
d

array([[ 0.14095745],
       [-0.1687981 ],
       [ 0.24451109],
       [-0.21667044]])

In [33]:
pd.DataFrame(d).describe()

0
count  4.000000
mean   3.836730
std    1.154701
min    2.736375
25%    2.918714
50%    3.766036
75%    4.684052
max    5.078473

In [30]:
e = preprocessing.StandardScaler(with_std=True).fit_transform(a)
e

array([[ 0.71584855],
       [-0.85723654],
       [ 1.2417429 ],
       [-1.10035491]])

In [31]:
pd.DataFrame(e).describe()

0
count  4.000000
mean   0.000000
std    1.154701
min   -1.100355
25%   -0.918016
50%   -0.070694
75%    0.847322
max    1.241743